export const CATEGORIES = [
  { value: "music", label: "Music" },
  { value: "programming", label: "Programming" },
  { value: "language", label: "Language" },
  { value: "art", label: "Art" },
  { value: "cooking", label: "Cooking" },
  { value: "fitness", label: "Fitness" },
  { value: "business", label: "Business" },
  { value: "academic", label: "Academic" },
  { value: "crafts", label: "Crafts" },
  { value: "photography", label: "Photography" },
  { value: "writing", label: "Writing" },
  { value: "design", label: "Design" },
  { value: "home-garden", label: "Home & Garden" },
  { value: "dance", label: "Dance" },
  { value: "technology", label: "Technology" },
  { value: "sports", label: "Sports" },
  { value: "health-wellness", label: "Health & Wellness" },
  { value: "finance", label: "Finance" },
  { value: "communication", label: "Communication" },
];